# Default values for kube-ts-react-client
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 2

image:
  repository: kubejs/kube-ts-react-client
  tag: 1.1.16
  pullPolicy: Always
  containerPort: 80

livenessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 60
  periodSeconds: 60

readinessProbe:
  httpGet:
    path: /
    port: 80
  initialDelaySeconds: 5
  periodSeconds: 10

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nameOverride: ''
fullnameOverride: ''

service:
  port: 80
  targetPort: 80

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
  hosts:
    - client.mariuszrajczakowski.me
  path: /
  tls:
    - hosts:
      - client.mariuszrajczakowski.me

nodeSelector: {}

tolerations: []

affinity: {}

# Secret [remove "{}", uncomment and change the values below]
secret: {}
  # KNEX_PASSWORD: password
  # KNEX_USER: root
  # SMTP_USER: user
  # SMTP_PASS: password
  # JWT_SECRET: secret
  # LOGGLY_TOKEN=logglyToken
  # LOGGLY_SUBDOMAIN=logglyUser

# Configmap [remove "{}", uncomment and change the values below]
configMap: {}
  # KNEX_DATABASE: database
  # KNEX_CLIENT: mysql
  # KNEX_HOST: localhost
  # SMTP_HOST: localhost
  # SMTP_FROM: noreply@example.com
  # SMTP_PORT: 465
  # SMTP_IGNORE_TLS: true
  # SMTP_SECURE: true
  # SMTP_REQUIRE_TLS: true
  # LOGGER_TYPE=winston
  # WINSTON_LOGGER_TYPE=loggly
  # LOGGLY_JSON=true
  # LOGGLY_TAGS=tag1,tag2


