secret: 
  KNEX_PASSWORD: $DEPLOY_KNEX_PASSWORD
  KNEX_USER: $DEPLOY_KNEX_USER
  SMTP_USER: $DEPLOY_SMTP_USER
  SMTP_PASS: $DEPLOY_SMTP_PASS
  JWT_SECRET: $DEPLOY_JWT_SECRET
  LOGGLY_TOKEN: $LOGGLY_TOKEN
  LOGGLY_SUBDOMAIN: $LOGGLY_SUBDOMAIN

configMap:
  KNEX_DATABASE: $DEPLOY_KNEX_DATABASE
  KNEX_CLIENT: $DEPLOY_KNEX_CLIENT
  KNEX_HOST: $DEPLOY_KNEX_HOST
  SMTP_HOST: $DEPLOY_SMTP_HOST
  SMTP_FROM: $DEPLOY_SMTP_FROM
  SMTP_PORT: $DEPLOY_SMTP_PORT
  SMTP_IGNORE_TLS: $DEPLOY_SMTP_IGNORE_TLS
  SMTP_SECURE: $DEPLOY_SMTP_SECURE
  SMTP_REQUIRE_TLS: $DEPLOY_SMTP_REQUIRE_TLS
  LOGGER_TYPE: $LOGGER_TYPE
  LOGGLY_JSON: $LOGGLY_JSON
  WINSTON_LOGGER_TYPE: $WINSTON_LOGGER_TYPE
  LOGGLY_TAGS: $LOGGLY_TAGS
  
